### ISSUE TITLE
Dereference link to Python binary in Python discovery part

### ISSUE THREAD

**Issue by fridex** [thoth-station/package-extract#302]
**Is your feature request related to a problem? Please describe.**

As a user of Thoth, I would like to know where the link to Python version binary ends. This is an extension to PR https://github.com/thoth-station/package-extract/pull/290/ introduced by @bissenbay where we detect Python version and Python binaries.

**Describe the solution you'd like**

As of now, we propagate `link` which states where the Python interpreter is located. It would be great to also introduce `link_dereferenced` which will traverse links and point to the final binary which is used. If dereferencing cannot be done, the `link_dereferenced` would be stated to `None` indicating the link dereference cannot be done. The link dereference should limit number of traversals not to end-up in link-loop.

**Comment by bissenbay** [comment]
@fridex Just want to make sure that we are not going to implement the functionality which we already implemented.
If I run `ls -l /usr/bin/python*` on my machine I can see these output:
```
/usr/bin/python -> python2
/usr/bin/python2 -> python2.7
/usr/bin/python2.7
```
Following, this piece of code
```python
import os
os.path.realpath('/usr/bin/python')
``` 
will show me below
`/usr/bin/python2.7`
If you notice it is not returning `/usr/bin/python2` instead it is returning the latest. I will go down until the link refers to itself.
Just wondering if `deferencing` is trying to do the same stuff?
We actually use `realpath` at https://github.com/thoth-station/package-extract/blob/master/thoth/package_extract/image.py#L489

**Comment by fridex** [comment]
Agh, right! I missed the `realpath` call. Closing this then :wink: :+1:

**Comment by fridex** [comment]
Reopening - one thing that came to my mind. A symlink can be relative and absolute. If we see a symlink `/usr/bin/python2` pointing to `/usr/bin/python2.7`, will there be used Python from the extracted image or from the base image where solver runs? The latter may cause issues as these binaries do not necesary exist. In other words - we will need to probably explicitly traverse symlinks and inject base path which points to the extracted container image location, instead of relying on `os.path.realpath` which dereferences relatively to container image base.

**Comment by bissenbay** [comment]
@fridex I starting from debugging and try to see where each `link` points to adding below code:
```python
if os.path.islink(py_path):
            _LOGGER.debug(py_path)
            _LOGGER.debug(os.readlink(py_path))
```
And this prints:
```
1)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m-x86_64-config
/usr/libexec/platform-python3.6m-x86_64-config
2)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python3
/etc/alternatives/python3
3)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m-config
/usr/libexec/platform-python3.6m-config
4)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6-config
python3.6m-config
5)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6
/usr/libexec/platform-python3.6
6)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python3-config
/etc/alternatives/python3-config
7)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m
/usr/libexec/platform-python3.6m
8)
/tmp/tmpq3eqbx46/rootfs/usr/bin/python2
python2.7
```
As we can see 1, 2, 3, 5, 6, 7 are pointing to the base image where solver runs and 4, 8 are pointing to the python interpreter of the image we are analyzing because there is no /etc or /usr

**Comment by bissenbay** [comment]
@fridex What should I do if the path links to the python interpreter of the base image where solver runs instead of the analyzed image? Should I just skip it and assing `null`?

**Comment by bissenbay** [comment]
> @fridex I started debugging and see where each `link` points to by adding the lines below:
> 
> ```python
> if os.path.islink(py_path):
>             _LOGGER.debug(py_path)
>             _LOGGER.debug(os.readlink(py_path))
> ```
> 
> And this prints:
> 
> ```
> 1)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m-x86_64-config
> /usr/libexec/platform-python3.6m-x86_64-config
> 2)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python3
> /etc/alternatives/python3
> 3)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m-config
> /usr/libexec/platform-python3.6m-config
> 4)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6-config
> python3.6m-config
> 5)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6
> /usr/libexec/platform-python3.6
> 6)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python3-config
> /etc/alternatives/python3-config
> 7)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m
> /usr/libexec/platform-python3.6m
> 8)
> /tmp/tmpq3eqbx46/rootfs/usr/bin/python2
> python2.7
> ```
> 
> As we can see 1, 2, 3, 5, 6, 7 are pointing to Python of the base image where solver runs and 4, 8 are pointing to Python of the image we are analyzing because there is no /etc or /usr

Regarding 4, it is tricky because if I run `os.path.realpath(py_path)` it prints `/usr/libexec/platform-python3.6m-config` which is pointing to the base image's Python.
However, 8 is good, it is pointing to `/tmp/tmpq3eqbx46/rootfs/usr/bin/python2.7`

**Comment by fridex** [comment]
> > @fridex I started debugging and see where each `link` points to by adding the lines below:
> > ```python
> > if os.path.islink(py_path):
> >             _LOGGER.debug(py_path)
> >             _LOGGER.debug(os.readlink(py_path))
> > ```
> > 
> > 
> > And this prints:
> > ```
> > 1)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m-x86_64-config
> > /usr/libexec/platform-python3.6m-x86_64-config
> > 2)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python3
> > /etc/alternatives/python3
> > 3)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m-config
> > /usr/libexec/platform-python3.6m-config
> > 4)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6-config
> > python3.6m-config
> > 5)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6
> > /usr/libexec/platform-python3.6
> > 6)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python3-config
> > /etc/alternatives/python3-config
> > 7)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python3.6m
> > /usr/libexec/platform-python3.6m
> > 8)
> > /tmp/tmpq3eqbx46/rootfs/usr/bin/python2
> > python2.7
> > ```
> > 
> > 
> > As we can see 1, 2, 3, 5, 6, 7 are pointing to Python of the base image where solver runs and 4, 8 are pointing to Python of the image we are analyzing because there is no /etc or /usr
> 
> Regarding 4, it is tricky because if I run `os.path.realpath(py_path)` it prints `/usr/libexec/platform-python3.6m-config` which is pointing to the base image's Python.
> However, 8 is good, it is pointing to `/tmp/tmpq3eqbx46/rootfs/usr/bin/python2.7`

Yes, this looks like the issue which was described before - relative and absolute symlinks. I think the solution is to drop using `os.path.realpath` and do traversal of links as you have done before (check if the link is relative, if not, adjust path to respect where the analyzed image is extracted).
