### ISSUE TITLE
Make sure pre-commit does not report any issues in this repo

### ISSUE THREAD

**Issue by fridex** [thoth-station/package-extract#426]
@fridex @harshad16 I have spent huge amount of time fixing `pre-commit` issues in this repo and really couldn't do much, could you please help with that?

_Originally posted by @bissenbay in https://github.com/thoth-station/package-extract/issues/425#issuecomment-733048777_

**Comment by harshad16** [comment]
I will take this. 
/assign @harshad16 
/unassign @bissenbay

**Comment by bissenbay** [comment]
> I will take this.
> /assign @harshad16
> /unassign @bissenbay

thanks @harshad16

**Comment by fridex** [comment]
Duplicate of https://github.com/thoth-station/package-extract/issues/417, closing.
