### ISSUE TITLE
Automatically detect Python modules present in container images analyzed

### ISSUE THREAD

**Issue by fridex** [thoth-station/package-extract#450]
**Is your feature request related to a problem? Please describe.**

As Thoth user, I would like to know what packages are present in container images. As of now, we provide information about Python files (setup.py specifically) present in the container image which is often not sufficient for consumers.

Related: https://github.com/thoth-station/adviser/issues/1926

**Describe the solution you'd like**

Have a mechanism that can find out what packages are present in the container images. As we do not want to execute any third-party code, we should have this ideally static. Or, make sure we execute only bits necessary to obtain package name (and optionally package version) information.

**Comment by goern** [comment]
Do we want this as a `thamos` output? or a website? API?

/triage needs-information
/kind feature

**Comment by fridex** [comment]
> Do we want this as a `thamos` output? or a website? API?

Basically have this available as part of package-extract result that is available on user-api endpoint. In that case, we will see what is present inside container images - what RPM packages, what Python packages, what shared objects and so. It could be visualized as part of https://github.com/thoth-station/core/issues/294

**Comment by goern** [comment]
sounds good! 
/remove-triage needs-information
/triage accepted
/priority important-soon
/help
