### ISSUE TITLE
Build-check failing

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/package-extract#489]
**Describe the bug**

Image build test is failing for last opened PRs. See https://tekton.operate-first.cloud/#/namespaces/opf-ci-pipelines/pipelineruns/aicoe-pipelinerun-6f64d095-b8f9-4104-bfec-b3f43e32ba50?pipelineTask=aicoe-pipelinerun-6f64d095-b8f9-4104-bfec-b3f43e32ba50-pr-8ccxl&step=condition-check-deploy-comment-check&view=details

**Comment by harshad16** [comment]
Fixed along with #485

**Comment by mayaCostantini** [comment]
Thanks @harshad16 :+1: Closing this issue.
