### ISSUE TITLE
Requirements.txt and Pipfile are not in sync

### ISSUE THREAD

**Issue by VannTen** [thoth-station/package-extract#497]
**Describe the bug**
The requirements.txt and Pipfile have different indications

**To Reproduce**
pipenv update --dev
pipenv run python setup.py test

**Expected behavior**
test suite runs

**Additional context**
See failing test in #494

**Proposed resolution**
Remove `requirements.txt`

@mayaCostantini
@harshad16
wdyt ?

**Comment by harshad16** [comment]
If we remove requirements.txt, is there a way for pyproject.toml or setup.py to read dependencies from pipfile.
we would have to keep a function in setup.py to do this , right?

**Comment by VannTen** [comment]
https://setuptools-pipfile.readthedocs.io/ seems to fit the bill
