### ISSUE TITLE
verify that metrics are flowing..

### ISSUE THREAD

**Issue by goern** [thoth-station/package-extract#69]
@hemajv could you provide a doc how we could check that metrics are flowing?

**Comment by fridex** [comment]
BTW @durandom, do you have a naming schema for metrics? Or do you assign their names systematically (e.g. <producer_name>-<metric_name>)? IMHO once we start providing more and more metrics, the naming could be important.

**Comment by durandom** [comment]
I dont have a scheme for metrics and that is indeed a problem with the metrics space in general. Everybody comes up with their own names. The <producer_name> would be in a label I guess

**Comment by goern** [comment]
packages-releases-job is pushing to http://pushgateway-thoth-test-core/
