### ISSUE TITLE
Setup protect branch for this repo

### ISSUE THREAD

**Issue by fridex** [thoth-station/package-extract#88]

**Comment by goern** [comment]
I think its done, whats missing?!

**Comment by fridex** [comment]
> I think its done, whats missing?!

Mh... I was not prompted for admin rights to merge a PR - I think there is not setup review request.

**Comment by goern** [comment]
True, right now it does not require approved reviews to merge something, as that would break the kebechet-auto-gate pipeline...

**Comment by fridex** [comment]
Ah, ok. Now I see. Thanks!
